language: cpp
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
      - keithw/glfw3
    packages:
      - gcc-5
      - g++-5
      - clang-3.6
      - build-essential git cmake libfreeimage-dev
      - cmake-curses-gui
      - libopenblas-dev libfftw3-dev liblapacke-dev
      - libboost-all-dev
      - opencl-headers
      - libglfw3-dev libfontconfig1-dev
script:
  - git clone --recursive --single-branch --branch v3.5.0 https://github.com/arrayfire/arrayfire.git
  - cd arrayfire
  - mkdir -p build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TEST=OFF
  - make && sudo make install
  - cd ../../pytorch-inference
  - mkdir build && cd build
  - cmake --build . --target test_all -- -j 4
compiler:
  - gcc
  - clang
os:
  - linux
branches:
  only:
    - master
    - dev